### ISSUE TITLE
Limit single-tenant Kafka source use of resources

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/eventing-kafka#1008]
**Problem**
A short explanation of the problem, including relevant restrictions.

Today single-tenant Kafka source when running has no resource limits set - effectively taking as much  (or as little) CPU as available in Kubernetes running the node. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

System Integrator
System Operator

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

I have run tests and verified that without resource limits pod will be taking as much resources as it can get.

After fixing the problem we should see that pod resource consumption is limited.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by aslom** [comment]
@lionelvillard WDYT?

**Comment by lionelvillard** [comment]
autoscaling does not work without limits, so +1.

**Comment by aslom** [comment]
It seems that using the same limits as other KnE components would make sense such as IMC dispatcher:

https://github.com/knative/eventing/blob/c820f4239730dacf5b2e0e5eed67a496bdc9b424/pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go#L82

```
							Resources: corev1.ResourceRequirements{
								Requests: corev1.ResourceList{
									corev1.ResourceCPU:    resource.MustParse("125m"),
									corev1.ResourceMemory: resource.MustParse("64Mi"),
								},
								Limits: corev1.ResourceList{
									corev1.ResourceCPU:    resource.MustParse("2200m"),
									corev1.ResourceMemory: resource.MustParse("2048Mi"),
								},
							},
```
