### ISSUE TITLE
v0.25 request to convert CR from an invalid group/version: messaging.knative.dev/v1alpha1

### ISSUE THREAD

**Issue by terman37** [knative-sandbox/eventing-kafka#1030]
**Describe the bug**
after installing v0.25.4

error when trying to get kafkachannels:
$ kubectl get kc
returns
Error from server: request to convert CR from an invalid group/version: messaging.knative.dev/v1alpha1

 **To Reproduce**
install knative serving / eventing / & kafkachannel using:
```
# Serving
kubectl apply -f https://github.com/knative/serving/releases/download/v0.25.2/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.25.2/serving-core.yaml

# Istio
kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.25.1/net-istio.yaml

# Eventing
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.25.4/eventing-crds.yaml
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.25.4/eventing-core.yaml

# inmemorychannel
kubectl apply -f https://github.com/knative/eventing/releases/download/v0.25.4/in-memory-channel.yaml

# Kafkabroker
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.25.4/eventing-kafka-controller.yaml
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/v0.25.4/eventing-kafka-broker.yaml

# kafkasource & kafkachannel
kubectl apply -f https://github.com/knative-sandbox/eventing-kafka/releases/download/v0.25.6/source.yaml
kubectl apply -f https://github.com/knative-sandbox/eventing-kafka/releases/download/v0.25.6/channel-consolidated.yaml

```

 **Knative release version**
v0.25

 **Additional context**
we used to have v0.20.0 installed, then we tried to upgrade installing from minor to minor release
then we decided to uninstall all resources and try from fresh install

**Comment by pierDipi** [comment]
Hi @terman37, the [upgrade process](https://knative.dev/docs/install/upgrade/upgrade-installation/) requires that you need to run some post-install jobs.

Did you run them?

**Comment by terman37** [comment]
Hello @pierDipi, 
i've not seen any mention about upgrade jobs in the release infos for eventing-kafka.
any idea where to find it?

Thx

**Comment by pierDipi** [comment]
We don't have docs for eventing-kafka specifically, the post-install job is in the release assets (if there isn't one for a particular version you don't need to run it).

**Comment by terman37** [comment]
Ok, thank you.
I think i've found the jobs you mentionned here:
https://github.com/knative-sandbox/eventing-kafka/tree/release-0.22/config/post-install

but release note is empty :-( and those files are not in assests.
https://github.com/knative-sandbox/eventing-kafka/releases/tag/v0.22.0

Maybe this can be added.

Anyway we manage to fix the problem, we reinstalled v.0.20.0 and cleanup some knative objects we forgot to clean.
then uninstall everything and restart with fresh install on v0.25

Thx
