### ISSUE TITLE
Upgrading v0.18.1 fails if a KafkaChannel already exists

### ISSUE THREAD

**Issue by devguyio** [knative-sandbox/eventing-kafka#116]
**Describe the bug**
Given:

1. An existing knative cluster
1. An existing Knative Kafka channel with an older version (e.g. `v0.17.5`)

Applying the `v0.18.1` Kafka channel yaml fails with following error and the upgrade fails
```
The Deployment "kafka-ch-dispatcher" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

 **Expected behavior**
Applying the yaml should succeed and upgrade should complete successfully

 **To Reproduce**
1. Install Knative Eventing and Knative Kafka Channel `v0.17.5`
1. Create a `KafkaChannel`
1. Upgrade Eventing: Apply the Knative Eventing yaml `v0.18.3` 
1. Apply the Knative Kafka Channel yaml `v0.18.1`

 **Knative release version**
v0.18.3

 **Additional context**
Pre `v0.18` Kafka Channel controller created the kafka-dispatcher deployment, while starting `v0.18` it seems the deployment is precreated by default in the release yaml but it doesn't expect that another deployment exists. Hence the failure.

**Comment by aliok** [comment]
Fixed for 0.18 with https://github.com/knative/eventing-contrib/pull/1660
Fixed for master (0.19) with https://github.com/knative-sandbox/eventing-kafka/pull/168

@devguyio feel free to close this ticket.
