### ISSUE TITLE
Provide at least once delivery guarantees in Kafka Channel

### ISSUE THREAD

**Issue by devguyio** [knative-sandbox/eventing-kafka#118]
**Problem**
Given the eventing contrib  KafkaChannel, with no subscriber based offset, it is impossible to provide at least once delivery guarantees. Retries and dead letter queue are the user's best options.

**Comment by lionelvillard** [comment]
@devguyio what do you mean "with no subscriber based offset"? Each subscriber gets its own consumer group. Isn't this enough?

**Comment by lionelvillard** [comment]
I talked to @devguyio and it seems we are in agreement that for now the only thing we need is making retries the default to at least support broker upgrades. Later on we'll provide way to customize the behavior.

**Comment by matzew** [comment]
sounds good to me on the retires!

**Comment by lionelvillard** [comment]
I also want to retire :-)
