### ISSUE TITLE
Stop consumer groups timeout in the second time ResetOffset

### ISSUE THREAD

**Issue by senayuki** [knative-sandbox/eventing-kafka#1194]
## Expected Behavior
ResetOffset works normally

## Actual Behavior
After the first successful resetoffset, FailedToStopConsumerGroups will appear in subsequent attempts. Kafka channel controller show me "Failed to stop one or more ConsumerGroups", "timed out waiting for the condition".
At this time, my sink can no longer receive messages.

## Steps to Reproduce the Problem

1. Create a new broker with subscription
2. Create a ResetOffset resource for a subscription, and got "True"
3. Create a ResetOffset in the same ~~subscription~~ KafkaChannel again, got "FailedToStopConsumerGroups"
4. Restart the dispatcher, subscription resetoffset will work again 

## Additional Info
Kafka Channel 1.1.2

As I mentioned above, restarting the dispatcher can solve the problem, ~~but restarting the controller is invalid. I think the problem may lie in the data plane.~~ Restarting controller is worked, but dispatcher need 60s to release lock. 
I observed the dispatcher logs and compared the two logs. All I could find was that the second time there was no new connection, "Stopping partition" was output normally, and the "Cleanup handler" was output normally in a short time, while the controller timed out after about ten seconds. 

I really don't know where to troubleshoot and solve the problem next.
Two dispatcher logs are attached below.

BTW, how to enable debug log-level for kafka channel controller and dispatcher?

**Comment by aliok** [comment]
cc @travis-minke-sap @eric-sap

**Comment by eric-sap** [comment]
Debug logging for both components is controlled with the same configmap, "config-logging" in the system namespace (typically "knative-eventing").  This also controls logging for other eventing components.  For example:

```
$ kubectl -n knative-eventing get configmap config-logging -o yaml
apiVersion: v1
data:
  loglevel.controller: info
  loglevel.webhook: info
  zap-logger-config: |
    {
      "level": "info",
      ....
    }
kind: ConfigMap
...
```

If you change the "level":"info" to "level":"debug" then the controller, receiver, and dispatchers will immediately begin debug logging (no need to restart).

There is also another level of debugging that is sarama-specific.  It can be enabled by changing "enableLogging: false" to "enableLogging: true" in the sarama section of the "config-kafka" configmap.  Changing that setting will restart the components (controller, receiver, dispatchers) automatically.  Sarama debugging is typically primarily useful if the actual kafka calls are having trouble (vs. a bug in the dispatcher), for example, if the brokers are misconfigured or there are other network issues.  Ordinarily the config-logging change is all that is of interest.

**Comment by senayuki** [comment]
Hey, thanks for your reply
First, respond to some use cases about this situation. Deleting the first ResetOffset has no effect. And the scope of influence is the entire KafkaChannel rather than the Subscription.

I have printed the debug log, but I still don't know why the controller thinks it times out, the dispatcher seems to have handled normally.
Attach the debug logs of the controller and dispatcher, which can be divided into normal and failed

[dispatcher_failed.log](https://github.com/knative-sandbox/eventing-kafka/files/8839491/dispatcher_failed.log)
[dispatcher_normal.log](https://github.com/knative-sandbox/eventing-kafka/files/8839492/dispatcher_normal.log)
[controller_failed.log](https://github.com/knative-sandbox/eventing-kafka/files/8839510/controller_failed.log)
[controller_normal.log](https://github.com/knative-sandbox/eventing-kafka/files/8839511/controller_normal.log)

**Comment by senayuki** [comment]
> Hey, thanks for your reply First, respond to some use cases about this situation. Deleting the first ResetOffset has no effect. And the scope of influence is the entire KafkaChannel rather than the Subscription.
> 
> I have printed the debug log, but I still don't know why the controller thinks it times out, the dispatcher seems to have handled normally. No matter whether resetoffset succeeds or fails, the dispatcher log doesn't seem to print out the Control Protocol response related log. I'm really not sure whether the response is normal. But if there is a connection problem between two pods, why is the first time (successful attempts) response normal? Or is it possible that this is associated with "managed group lock"? Attach the debug logs of the controller and dispatcher, which can be divided into normal and failed
> 
> [dispatcher_failed.log](https://github.com/knative-sandbox/eventing-kafka/files/8839491/dispatcher_failed.log) [dispatcher_normal.log](https://github.com/knative-sandbox/eventing-kafka/files/8839492/dispatcher_normal.log) [controller_failed.log](https://github.com/knative-sandbox/eventing-kafka/files/8839510/controller_failed.log) [controller_normal.log](https://github.com/knative-sandbox/eventing-kafka/files/8839511/controller_normal.log)

Update: I capture package, I do belive dispatcher responsed OpCode 11 and controller ACK(OpCode 0xff) in both success and failure cases. 
But I still dont know why controller cant continue the process instance timeout, but persistently overtime in second attempt.

**Comment by senayuki** [comment]
The problem has been solved. This is really a serious bug.
When ReconcileConnections, the services in the service pool will be reused, and the MessageHandler contains the information of the ResetOffset resource (NamespacedName) during initialization.

During the second attempt, the service is reused, and the handler is not updated. As a result, the response information from the dispatcher is recorded as the ResetOffset resource during initialization. The "waitForAsyncCommandResult" will never get the result of the second attempt.

**Comment by eric-sap** [comment]
Amazing work!  Thank you!

**Comment by travis-minke-sap** [comment]
Yeah, great job - I think we found the new owner of the DistributedChannel / ResetOffset implementation ; )

**Comment by travis-minke-sap** [comment]
Yes, the Control-Protocol is rather complicated.  It was intended to facilitate data-plane <--> control-plane communication in Knative but never really took off.  The ResetOffset implementation was the first (and only) trial of it.

I also want to make sure you are aware of the "new" Kafka implementations in the eventing-kafka-broker repository.  These java based implementations are replacing those in the eventing-kafka repository, which are likely to be deprecated soon.  The new implementation does not (afaik) support the ability to move offsets (ResetOffset or similar) but maybe there are alternative options for doing so.  I just didn't want you to spend too much time on stale implementations without understanding the implications.

**Comment by senayuki** [comment]
Thank you for your introduction. I have got some important information. I will reconsider.
