### ISSUE TITLE
eventing.knative.dev/scope: namespace does not work with distributed kafka channel

### ISSUE THREAD

**Issue by AceHack** [knative-sandbox/eventing-kafka#126]
**Describe the bug**
In the previous version eventing.knative.dev/scope: namespace would allow me to connect to different Kafka clusters at least at the namespace level.

 **Expected behavior**
The ability to connect to more than one kafka cluster with knative.

 **To Reproduce**
Add the eventing.knative.dev/scope: namespace to a kafka channel (distributed) and nothing happens.

 **Knative release version**
nightly

 **Additional context**
We don't absolutely need eventing.knative.dev/scope: namespace to work, we just need a way to connect to multiple kafka clusters, like maybe even specifying it at the KafkaChannel level similar to how it is in KafkaSource.

**Comment by lionelvillard** [comment]
Related to https://github.com/knative-sandbox/eventing-kafka/issues/157.

@AceHack assuming https://github.com/knative-sandbox/eventing-kafka/issues/157 gets resolved by allowing specifying the config at the KafkaChannel level, are you ok if we deprecate `eventing.knative.dev/scope` ?

**Comment by AceHack** [comment]
Any update?

**Comment by lionelvillard** [comment]
No progress I'm afraid. We are having discussion in https://github.com/knative-sandbox/eventing-kafka/issues/157 but nothing concrete yet.

**Comment by ssandanshi** [comment]
Any updates on this?

**Comment by travis-minke-sap** [comment]
Yeah, I hadn't seen this one in a long while ; ).    Definitely something that we should support, and I don't see why the distributed implementation couldn't be made to work similar to consolidated version.  My time is going to be focused elsewhere for awhile (#588, #613, etc...) but I've added to my personal internal tracking list of things that Eric and I can look at.
