### ISSUE TITLE
Consolidated KafkaChannel marks Subscriptions Ready too early

### ISSUE THREAD

**Issue by devguyio** [knative-sandbox/eventing-kafka#134]
**Describe the bug**
[The Channel spec](https://github.com/knative/eventing/blob/master/docs/spec/channel.md) requires

> Channels MUST send events to all subscribers which are marked with a status of ready: "True" in the channel's status.subscribableStatus.subscribers (v1alpha1) or status.subscribers (v1beta1).

There is, however, a delay between the subscribers status being ready in the KafkaChannel status, and the startup of the partition consumer for the topic.

Any events sent to the channel during the window are not being sent to subscribers.

 **Expected behavior**
kafka-channel-dispatcher should not update the subscribers status if it isn't actually ready to send events to subscribers, so it doesn't violate the spec.

 **Additional context**
The KafkaDispatcher logic is

1. Create a sarama ConsumerGroup
    1. Start a `Consume()` go routine (async)
1. Errors? no-> mark subscription ready

The Consumer connects and joins the Kafka ConsumerGroup in step 2 which is async and can happen indeed after step 3. is executed.

**Solution idea** 
To have a status for the ConsumerGroup (ours, not Sarama) and set it to Ready once the actual join occurs (Sarama has a `Setup()` lifecycle callback that will be called on a successful join) and consequently mark the subscription ready only when the CG is ready

**Comment by vaikas** [comment]
Are you going to have both the Channel Reconciler and Dispatcher Reconciler updating the status fields? I'd be little concerned about having two controllers fighting over the Status fields.

**Comment by pierDipi** [comment]
Related to status updates: https://github.com/knative-sandbox/eventing-kafka/issues/98.

**Comment by lionelvillard** [comment]
Also related to https://github.com/knative/eventing/issues/3281.

**Comment by matzew** [comment]
also related: https://github.com/knative/eventing/pull/4280

**Comment by devguyio** [comment]
Chat thread summary

@devguyio 
> in the ChannelSpec
>> Channels MUST send events to all subscribers which are marked with a status of ready: "True" in the channel's status.subscribableStatus.subscribers (v1alpha1) or status.subscribers (v1beta1).

> currently for KafkaChannel, that means the subscriptions should be ready only when they have the underlying Kafka connection (Consumer) ready (joined) .
> now I wonder if instead, the KafkaChannel doesn't add the subscription to its status subscribers array until their Kafka Consumers are ready? not sure if that makes sense?

@vaikas 
> as in subscription should only look at the channel status to see when the requested subscription has made it to the status.
> Ok, so after having slept on this, and poking a little bit, I think readiness gate is not really what we want here. The channel can be ready, but a particular subscription might not be ready (by design). For that the Channel Subscriber Status array is there for. That is what Subscription looks at:
> https://github.com/knative/eventing/blob/master/pkg/reconciler/subscription/subscription.go#L295
> So, looking at the spec and after going back to the code, I think the right thing to do here is to look at having the control plane configure the Channel bits up to the point of can it receive traffic (receiver, dispatcher, etc.) and the Dispatcher (the dataplane for each subscription) will patch the subscriber status array with the subscribers with their perspective statuses once all the dataplaney things have been configured.
> Channel should be able to flip to ready even if there are no subscriptions to it, and a single subscription data plane failure should not mark the channel failed, but a particular subscription.
> wanted to explicitly point out that the dataplane should not be flipping the entire channel readiness bit but rather operate on the individual subscription status, and the Subscription reconciler keys off the individual ‘Channel Subscriber Status’ as per:
https://github.com/knative/eventing/blob/master/docs/spec/channel.md#channel-subscriber-status

@devguyio 
> The Channel readiness should be ready if all "channel" dataplane are in place, and the subscription readiness is orthogonal and per subscription.

**Comment by devguyio** [comment]
**Proposed Solution:**
1. Kafka Dispatcher owns the `Channel.Status.SubscribableStatus` object.
1. It makes sure that the subscription shows up in the `SubscribableStatus` once the consumer is ready, and taken out once it's not.
1. Above change can either be a patch, or an update if the there are no other reconcilers will step on each other toes
1. Leader Election should be enabled to solve the race between dispatcher replicas until a concrete solution can address that (we can have the leader aware of the replicas and once it detect they're down by one, it feels authorized to remove the subscription from the SubscribableStatus if the Consumer leaves the KafkaCluster)

**Comment by antoineco** [comment]
> We can have the leader aware of the replicas and once it detect they're down by one, it feels authorized to remove the subscription from the SubscribableStatus if the Consumer leaves the KafkaCluster

Does it mean the entire subscription is invalidated if _1_ replica becomes unavailable? If yes, why is that so? (disclaimer: I'm not familiar with the internals of that channel)

**Comment by vaikas** [comment]
FYI, threw something concrete around IMC to share:
https://github.com/knative/eventing/pull/4435

**Comment by devguyio** [comment]
@antoineco sorry I wrote the wrong proposition :D fixed now. 
> We can have the leader aware of the replicas and once it detect they're down to one, it feels authorized to remove the subscription from the SubscribableStatus if the Consumer leaves the KafkaCluster

does it make sense now?

**Comment by antoineco** [comment]
Under what circumstances does the "consumer" leave the Kafka cluster? When the subscription is deleted? If yes, how is it relevant how many replicas the dispatcher has?

**Comment by devguyio** [comment]
@antoineco the Consumer can leave in case a rebalance on the Kafka server takes place, or a network glitch or a disconnection. In such case, there can be other consumers in other replicas dispatching messages for the same subscription. So when we've two replicas, 1 & 2, and 2 gets killed, OOMed, ejected, etc, dispatcher 1 should know that it's authorized now no make the reflect the subscription readiness in the channel Status. There are a number of corner cases here but that's why this needs a thorough design.

**Comment by lionelvillard** [comment]
In the case of Kafka, I would consider a subscriber to be ready when its associated consumer group has been created. It means that the partition offsets has been initialized and for now on all events published to channel will be consumed by the subscriber.

I wonder if the control plane is the right place to create the consumer group (if not already the case). The benefit of this solution is there is no need for leader election, no need to update the subscriber status from the dispatcher.

@devguyio thoughts?

**Comment by antoineco** [comment]
@lionelvillard Does the existence of a consumer group guarantees that this consumer group is currently consuming events from the topic? Could the consumer group be created, then the consumer terminates, and nothing is actually interacting with Kafka? (disclaimer: like I said, I'm not familiar with the internals of this channel)

@devguyio I think it makes sense yes. I though there was something Kafka-specific to understand in your comment, but what you're describing is just the regular behaviour of an elected leader, where just one replica is allowed to perform writes to the objects' statuses. Ingress controllers work exactly like this too.

**Comment by antoineco** [comment]
Makes sense, thanks for clarifying!

**Comment by devguyio** [comment]
Still exists

**Comment by devguyio** [comment]
Fixed by #433
