### ISSUE TITLE
Consistent Support For Multiple Kafka Auth Secrets

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#15]
Currently the Azure EventHubs AdminClient supports multiple Kafka Authorization Secrets and the "normal" Kafka AdminClient does not.  It would be good to step back and define requirements around the consistent support for multiple Kafka instances.

**Background**
Azure EventHubs (Kafka compatibility / emulation) limit the number of EventHubs (Kafka Topics) can exist in a specific EventHub Namespace to 10.  The EventHub Namespaces each have distinct Authorization.  The current implementation supporting multiple Kafka Authorizations for EventHubs was put in place to work around this limitation by load-balancing across as many EventHub Namespaces (Kafka Auths) as a user might need.

This is obviously an edge use case in the Kafka community, and the more important issue is whether (and how) to support multiple Kafka instances going forward for multi-tenant type use cases.

**Comment by lionelvillard** [comment]
related to https://github.com/knative-sandbox/eventing-kafka/issues/157.

/remove-lifecycle stale.

**Comment by travis-minke-sap** [comment]
Closing due to recent refactor of distributed kafkachannel's sarama adminclient in PR #297.  That PR removed support for pooling multiple KafkaChannels in the EventHub use case and all admin client types (kafka, azure, custom) are currently restricted to a single Kafka Auth/Secret.  We can always open the appropriate PRs if/when multitenancy or multi-kafka support is tackled.
