### ISSUE TITLE
Dispatcher Retry & Dead Letter Queues

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#16]
Currently the implementation has custom retry logic which is preventing the use of the eventing MessageDispatcher.DispatchMessage()'s ability to send to the Dead Letter Queue.  Doing so would result in a separate Dead Letter Queue message for every retry attempt.  Need to look at retry implementations in conjunction with the Knative Eventing implementations to design a more flexible solution.

**Comment by sbcd90** [comment]
Hi @travis-minke-sap , I would like to work on this. Is it possible to kindly assign this to me?

**Comment by davyodom** [comment]
/assign @sbcd90 
Sure, give it a shot! It's possible that some change might be required for the eventing library.  The goal here is to share library usage with eventing, but maintain the ability for a reasonable retry, some of which now spans the cloud event sdk (v2 usage coming in an open pr).  Some configurability might need to be added separately there or the knative library as per some discussions in the WG.  Take a look and sketch out your approach/proposal and we can discuss on Wednesday (we have a holiday until then)

**Comment by sbcd90** [comment]
Hi @davyodom , thanks a lot. I created a document to initially propose my approach & trigger further discussions.
https://docs.google.com/document/d/1z3psNbyH7YnskzgzjLPdOFcLel4npld0ea7YwUJkZ4o/edit?usp=sharing

**Comment by travis-minke-sap** [comment]
Hi @sbcd90 - Thanks for putting together the proposal!  Unfortunately I don't think what you're suggesting will meet our requirements / needs.  Aside from being rather heavy-weight in it's use of another Topic / Consumer, it breaks our `in-order` guarantees by going async.  I haven't done much investigation into possible solutions as of yet, but my initial thought was one of the following...

  - A small change to what we currently have whereby we detect the fact that we're on the "last" retry attempt, and then pass the DeadLetter to the MessageDispatcher.  This is essentially the `Max no. of retries reached` decision point in your proposed solution.  I have no idea how easy/hard that might be.

  - Stepping back and taking a larger view by digging into the Knative MessageDispatcher implementation to see whether it could natively support the "retry" ability for all channels (optional, configurable, etc.) thereby eliminating the need for our wrapping retry library.  This might be achieved via the native CloudEvent retry capability which I don't believe Knative is currently making use of.

...and we're certainly open to other ideas / approaches as well as long as they preserve our `at-least-once` / `in-order` guarantees and don't impact cluster resource consumption and / or performance too much.

**Comment by sbcd90** [comment]
Hi @travis-minke-sap , thanks a lot for sharing your thoughts. I'll focus on point 1 first.
& then once it is solved, look into point 2.

**Comment by davyodom** [comment]
Somewhat relevant here : https://github.com/knative/eventing/issues/2411

**Comment by travis-minke-sap** [comment]
Hey there @sbcd90 - I was out for a couple days - I'll take a look at your PR now/soon ; )

**Comment by tminke** [comment]
In case anyone is still looking at this...

as part of the Sarama conversion #31 - I'll be handling the DLQ there so this should not be worked - will close once #31 is completed.

**Comment by sbcd90** [comment]
Thanks a lot @tminke for informing. Is introduction of ‘resolver’ still something that can be worked on?
