### ISSUE TITLE
Kafka client refactoring

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#188]
Refactor to have some more commonly shared "kafka client" code

## Admin client for the channel controller

* https://github.com/knative-sandbox/eventing-kafka/blob/1a46a74b179207ff6217484089cf5970e0716066/pkg/channel/consolidated/reconciler/controller/resources/client.go#L23-L28
* https://github.com/knative-sandbox/eventing-kafka/tree/c3e6f18ffe5dd67b36dcb42b7b3e95838e4ae4f8/pkg/channel/distributed/common/kafka/admin

## Normal dispatcher client:

* https://github.com/knative-sandbox/eventing-kafka/blob/1a46a74b179207ff6217484089cf5970e0716066/pkg/channel/consolidated/dispatcher/dispatcher.go#L85-L90
* https://github.com/knative-sandbox/eventing-kafka/blob/c3e6f18ffe5dd67b36dcb42b7b3e95838e4ae4f8/pkg/channel/distributed/common/kafka/sarama/sarama.go

**Comment by aliok** [comment]
/close

I say this is done via https://github.com/knative-sandbox/eventing-kafka/issues/268 and https://github.com/knative-sandbox/eventing-kafka/issues/298

Reopen if you had something else in your mind
