### ISSUE TITLE
KafkaChannel Topic Deletion Handling

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#215]
**Problem**
It has been asked whether it is desirable to delete Kafka Topics when KafkaChannels are finalized as is currently implemented.

On the one hand, the Topic can be considered a sub-resource whose creation is driven/owned by the KafkaChannel reconciliation, and should thus have it's lifecycle completely owned by the controller.  On the other hand, it might be that users are trying to simply expose access to existing Kafka Topics to their Knative eventing infrastructure to produce/consume against, and don't want to manage the creation/deletion with the Controller.

> Note that duplicate "creation" of the Kafka Topic is "safe" in that Kafka will just respond that the "topic already exists".  

This Issue is to facilitate discussion of what functionality the Kafka Channel implementations should provide...
 - Delete Topics upon Kafka Finalization as is currently implemented
 - Never delete Topics and leave it to the user
 - Provide a configuration hook to allow users to specify the intended deletion behavior (possible a field in the KafkaChannel CRD?)
  - Other options?

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Event Producer.  (Users)

**Exit Criteria**
Not a bug - just a "requirements" issue - ideally we'll settle on an approach and make change (if necessary) to both KafkaChannel implementations.

**Time Estimate (optional):**
?

**Additional context (optional)**
Slack thread initiating the discussion... https://knative.slack.com/archives/CR2141CGY/p1604409613124200

**Comment by slinkydeveloper** [comment]
> Delete Topics upon Kafka Finalization as is currently implemented

To me it sounds like we should keep as is, as **default** behaviour. The reason is that the user must not rely on the KafkaChannel internals, otherwise we're leaking these details.

On the other hand, I see how this could be useful, so we could have an option to allow it, but IMO it should be "hidden" like in some ConfigMap or with some annotation on the KafkaChannel resource, but definitely not exposed as a field in the CRD for the reasons above explained.

**Comment by patrickriordan** [comment]
I'm trying to use knative eventing like travis-minke-sap mentioned and this feature would be great to have.

I want to let knative consume from an existing kafka topic without creating an additional one specifically for the broker or channel. It seems like having two topics that contain the same data would be extra overhead and cause performance issues down the line. 

So pointing the kafka-channel to the already existing topic seems like the correct way, and having the option to disable deletion would support that use case.

**Comment by lionelvillard** [comment]
Definitively something we need to support. Not the first time I hear people asking for it.

**Comment by slinkydeveloper** [comment]
> I want to let knative consume from an existing kafka topic without creating an additional one specifically for the broker or channel. It seems like having two topics that contain the same data would be extra overhead and cause performance issues down the line.

For that use case you need to use `KafkaSource`, `KafkaChannel` is not designed for it

**Comment by pierDipi** [comment]
People can use `KafkaSource` and `KafkaSink` for those use cases.

**Comment by patrickriordan** [comment]
Don't I lose the trigger functionality that comes with broker/trigger if I only use a source?  Is there anyway to keep the broker/trigger functionality without KafkaSource to Broker (which requires 2 kafka topics)? I haven't looked into KafkaSink yet.

I guess I could do filtering in the service and just setup a source for each service that wants to read from the kafka topic?

Sorry if this isn't the right place for this discussion btw

**Comment by pierDipi** [comment]
I thought we were talking about the KafkaChannel, but yes, that functionality is lost.

I think the Broker/Trigger model as it's designed and used can't expose implementation details (like Kafka topics) or the underlying channel.

> I guess I could do filtering in the service and just set up a source for each service that wants to read from the kafka topic?

Yes, you can do that, or maybe `KafkaSource` can support filtering events before sending them to a subscriber, which seems what you want.

> Sorry if this isn't the right place for this discussion btw

If you can open an issue would be great.

**Comment by slinkydeveloper** [comment]
> Yes, you can do that, or maybe KafkaSource can support filtering events before sending them to a subscriber, which seems what you want.

I recall this was discussed a while ago, cc @lionelvillard
