### ISSUE TITLE
Expose Sarama metrics through Prometheus

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#222]
**Problem**
Sarama metrics are not exposed.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

Metrics are documented there: https://godoc.org/github.com/Shopify/sarama

**Comment by travis-minke-sap** [comment]
Agreed that this would be good - it's been on our (SAP) radar regarding the "distributed" KafkaChannel.  We have the beginnings of this (single metric) here...

https://github.com/knative-sandbox/eventing-kafka/blob/master/pkg/channel/distributed/common/metrics/stats_reporter.go

**Comment by pierDipi** [comment]
It's probably worth considering contributing upstream using opentelemetry (it's not GA though), there is sarama integration with only the tracing bits: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/Shopify/sarama/otelsarama
