### ISSUE TITLE
KafkaChannel Status Alignment

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#26]
The architecture of the `eventing-sandbox/eventing-kafka` implementation is inherently different from that of `eventing-contrib/kafka`.  The former is, however, based on the same KafkaChannel CRD as the latter.  This means that the Status tracking is not exactly aligned for tracking the resources READY states.  Further we've never tracked K8S Endpoints directly and might want to do so.  This likely cannot be worked until plans for merging the two implementations are better defined.

**Comment by pierDipi** [comment]
This is similar to https://github.com/knative/eventing/issues/3094.

/assign
