### ISSUE TITLE
HA Controller Follow-Up

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#28]
This issue is a placeholder to look a bit deeper into the new HA Controller support being introduced in Knative once things have settled out a bit more.  Research as of the time of writing is captured below for reference, but is of course subject to change...

### Research...

The Knative Operator appears to be driving this use case.  It currently/previously had a list of hardcoded Controllers from Knative Serving that could be made HA with the specified number of replicas.  This is being expanded into Knative Eventing and being made a bit more dynamic via the use of the `knative.dev/high-availability: "true"` label.  Some of the core Controllers in the eventing repo have been labelled as such.  Nothing in the eventing-contrib repo has been labelled as of yet.

We would only want to run the main eventing-kafka controller in this HA mode if even that.  The Channel / Dispatcher (Kafka Producer/Consumer) Deployments will be scaled/managed in other ways.

The eventing-contrib/kafka implementation seems to propagate the`CONFIG_LEADERELECTION_NAME="config-leader-election-kafka"`  Environment Variable around but it's not clear how this is used (if at all?). The config YAML includes the corresponding ConfigMap `400-leader-election-config.yaml`.

There is some leader-election logic in the eventing webhook - but that just seems to validate/block creation of configmaps with unsupported controller lists?

#### Open Questions...
- Is this HA Controller concept intended to include the individual Channel Controllers?
- Does having an HA Controller buy us anything useful in production?  K8S will restart any failed controller Pods which will likely also just fail.  I suppose might protect against a "stuck / hung" Pod?
- Is this label only used by the Knative Operator?
- Does the Knative Operator deal with individual Channel Controllers like ours?
- What would be required of our controller implementation (if anything) in order to support leader-election?

#### References...
```
# Original Knative Operator Issue (Open)
https://github.com/knative/operator/issues/73

# Eventing PRs Which Added The HA Label To Ko YAML
https://github.com/knative/eventing/pull/3311
https://github.com/knative/eventing/pull/3324

# Knative Operator Docs On HA (probably not up to date with in-flight changes)
https://github.com/knative/operator/blob/master/docs/configuration.md#spechigh-availability

# HA Leader Election Docs From May
https://github.com/knative/docs/issues/2454
https://github.com/knative/docs/pull/2455/files
```

**Comment by eric-sap** [comment]
"high-availability" is the default behavior now, unless "sharedmain.WithHADisabled" is added (or the "--disable-ha" argument is added to the command-line args of the deployment), so I don't believe there's anything left to do for this issue explicitly.

Note that the distributed channel's dispatcher (and receiver) do not currently use the sharedmain functionality, and as such do not use the high-availability/leader-election code. If the dispatcher is changed to use sharedmain, it should probably, like the consolidated channel's dispatcher, use the "sharedmain.WithHADisabled" entry point.
