### ISSUE TITLE
Provide option for configuring initial offset in kafka source

### ISSUE THREAD

**Issue by itsmurugappan** [knative-sandbox/eventing-kafka#289]
**Problem**
Continuing the discussion on this [issue](https://github.com/knative/eventing-contrib/issues/1492) in the new repo.

Currently the kafka source starts from the newest offset. With this option the kafka source needs to be created before the producer sends message. This is not the case in most of the kafka use cases as producer is independent of the consumer. In these scenarios initial offset needs to be the earliest. 

If offset was already saved for a partition, sarama-cluster will resume consumption from that offset. The Config.Consumer.Offsets.Initial option is used only if no saved offset is present (first run for a consumer group)

https://github.com/Shopify/sarama/blob/0cdf4a6c31734ea9473b03a36fff21947a8e9d5c/config.go#L381

cc @slinkydeveloper @aliok

**Comment by itsmurugappan** [comment]
* What happens if a consumer group already exists, say with offset 100, but the user configures in kafka source an offset, say 200? - `The 200 will be ignored, as this is the initial offset`

* What happens if, similar to above, the user doesn't configure the offset first, then updates the kafka source cr and configures the offset with a value higher than the actual processing status - `The offset number will be taken into consideration only when the consumer group is not there`

* Should the KafkaSource continue to commit the offset when the initial offset is already configured? - `yes, instead of latest, we will specify earliest, i made change on kafka source and tested this out`

* KafkaSource spec fields ultimately are "templates" of the resource pods, what happens if we implement a scalable kafka source? Every instance should restart from that offset? Also note that this one might even create loops, because every time it would reset the consumer group state - `As mention above this is just initial offset when consumer group is not there`

* Similar to above, what happens if the kafkasource crashes and then restarts? Should it restart from the configured offset?
Should the offset and consumer group be exclusive fields, to avoid any of the above problems? But what if the user wants to set both the consumer group and the offset (which is reasonable if the consumer group does not exists)? - `it will start from the last committed offset , same as now`

* How do we communicate to the user such edge cases? - `Sarama gives 3 options for initial offset, if giving a specific offset number is complicated, we can limit to earliest and latest`

**Comment by slinkydeveloper** [comment]
> Sarama gives 3 options for initial offset, if giving a specific offset number is complicated, we can limit to oldest and newest, newest is default

That sounds better and it's trivially implementable, because the library takes care of it. I'm ok with that solution, although I still find weird how this is represented in the CRD semantic.

**Comment by lionelvillard** [comment]
Related to https://github.com/knative-sandbox/eventing-kafka/issues/157. The idea is to be able expose all Sarama config parameters, via a ConfigMap, including the initial offset.

**Comment by lionelvillard** [comment]
We talked about this during the Eventing WG meeting.

One possible solution, which seems appropriate for KafkaSource, is to add a new field in the KafkaSource spec for representing the initial offset. 

@itsmurugappan do you have some cycles to work on this feature?

**Comment by itsmurugappan** [comment]
Sure, I can work on this.
/assign

**Comment by lionelvillard** [comment]
feel free to reach out directly to me or on the slack eventing-sources channel.
