### ISSUE TITLE
Use KnCEConnectionArgs in consolidated channel dispatcher and possibly in other places

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#312]
**Describe the bug**
There's a `KnCEConnectionArgs` field in consolidated channel dispatcher args, but it is not used anywhere.

 **Expected behavior**
The field is used OR removed.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aliok** [comment]
cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
Is this still valid @aliok? I recall we talked about it and we agreed on having it configurable just at startup

**Comment by aliok** [comment]
/close

No, it is not valid. Both channel's implementations do `kncloudevents.ConfigureConnectionArgs(...)` properly now.
I now created https://github.com/knative-sandbox/eventing-kafka/pull/542 to completely remove the dispatcher arg thing.
