### ISSUE TITLE
Consolidated channel dispatcher is not getting the changes in config-kafka during runtime

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#318]
**Describe the bug**
Consolidated channel dispatcher is not getting the changes in config-kafka during runtime

Main problem: channel dispatcher doesn't get the changes in `config-kafka`
- Create a consolidated channel
- Change stuff in `config-kafka`
- Changes are read by the controller (besides the problems in https://github.com/knative-sandbox/eventing-kafka/issues/393), but not reflected in the channel dispatcher

There might be the same story for KafkaSource.

 **Expected behavior**
Similar to distributed channel, watch the changes, and apply them.

2 alternatives for channel:
- Watch the configmap in the controller, recreate the dispatcher
- Watch the configmap in the dispatcher

Same story for KafkaSource.

 **To Reproduce**
- Create a consolidated channel
- Change stuff in `config-kafka`
- Changes are not reflected in the channel dispatcher

 **Knative release version**
0.20

 **Additional context**
Noticed during https://github.com/knative-sandbox/eventing-kafka/pull/305

**Comment by aliok** [comment]
@slinkydeveloper @lionelvillard 

We currently mount the `config-kafka` to the dispatcher pod but when the configmap is modified, the pod doesn't know about it.

A. Watch the configmap in the controller, recreate the dispatcher (by deleting and recreating OR updating the dispatcher deployment?)
B. Watch and read the configmap in the dispatcher instead of mounting it as a volume
C. Pass the configmap as an env to the dispatcher


Which one makes more sense?

I think I would prefer C since we already do that in other places like source adapters. However, B might be the simplest with least effects.

**Comment by slinkydeveloper** [comment]
What about mounting the CM as volume and then use a file watcher? That's what we do in eventing-kafka-broker: no need for role bindings and friends and easy to implement

**Comment by aliok** [comment]
Sounds better. Let me check StackOverflow on how to do it :D

**Comment by aliok** [comment]
Similar to https://github.com/knative-sandbox/eventing-kafka/issues/399, I will wait until I hear more opinions on ML if we should implement this or not.

At least I fixed the problems in the controller regarding watching the configmaps.

**Comment by aliok** [comment]
For a unified channel implementation, I want to implement this also in consolidated channel if it exists in distributed channel.

ML discussion here: https://groups.google.com/g/knative-dev/c/VQuCXfAl8JQ

**Comment by aliok** [comment]
/reopen

I forgot the "Fixes: 318" text in https://github.com/knative-sandbox/eventing-kafka/pull/423

That PR was for refactoring only. More work is needed.

**Comment by aliok** [comment]
/close
Closing per https://github.com/knative-sandbox/eventing-kafka/issues/455

**Comment by aliok** [comment]
Summary: this is done in a different way. Instead of on-the-fly reloading in the dispatcher, we do this:
- Watch the configmap in controller and resync everything: https://github.com/knative-sandbox/eventing-kafka/pull/486
- Do a rolling update of the dispatcher deployment: https://github.com/knative-sandbox/eventing-kafka/pull/514

Same thing will be done in distributed channel: https://github.com/knative-sandbox/eventing-kafka/issues/455
