### ISSUE TITLE
KafkaSource should not create topics

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#334]
**Describe the bug**
When deploying a KafkaSource referencing a topic that does not exist, the topic will be automatically created. 

 **Expected behavior**

No topic should be created. An error should be propagated to the CR status section

 **To Reproduce**
Steps to reproduce the behavior.
Create a KafkaSource referencing a topic that does not exist.

 **Knative release version**
main

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by matzew** [comment]
If the server is not configured to prevent this, this will happen - that's a normal kafka thing.

**Comment by lionelvillard** [comment]
Interesting. Do you know if topics are automatically deleted? In any case, the source does not own the topic, which is good.

Make me think we should add a e2e test with`auto.create.topics.enable` set to false.

**Comment by matzew** [comment]
topics are not deleted.
and we have e2e setup with the auto create -> false now

/close
