### ISSUE TITLE
Configure MaxIdleConnection via CM ? 

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#357]
**Problem**
in IMC the `MaxIdleConection` settings can be configured via Config Map. But not for the kafka channel

**Exit Criteria**
would be good to have the same kind of tweak for this?

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by matzew** [comment]
looking here: https://github.com/knative-sandbox/eventing-kafka/pull/353/files and wondering about that "feature"

**Comment by slinkydeveloper** [comment]
We removed that from IMC for this reason: https://github.com/knative/eventing/issues/4469 :smile: If we need it, we can allow the configuration through envs

**Comment by matzew** [comment]
Something like `k -n knative-eventing patch configmap/config-kafka --type=merge --patch='{"data": {"maxIdleConns": "1000", "maxIdleConnsPerHost": "1000"}}'` is possible now 

/close
