### ISSUE TITLE
[mtsource] bandwidth rate limiter

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#369]
**Problem**
The current rate limiter controls how frequently events are allowed to happen. Since forwarding events is mostly network-bound, it makes more sense to rate limit the number of processed bytes to maximize resource utilization.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?
~1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
Why aren't Kafka quotas good enough? Because they're per broker?

**Comment by lionelvillard** [comment]
Kafka quotas are broker-side knobs, is that right?

**Comment by pierDipi** [comment]
Yes, right.

**Comment by pierDipi** [comment]
From https://kafka.apache.org/documentation/#design_quotas
>
> - Network bandwidth quotas define byte-rate thresholds (since 0.9)
> - Request rate quotas define CPU utilization thresholds as a percentage of network and I/O threads (since 0.11)

Not sure if this might work in your env.

A downside I was referring to is:
> By default, each unique client group receives a fixed quota as configured by the cluster. This quota is defined on a per-broker basis. Each client can utilize this quota per broker before it gets throttled. We decided that defining these quotas per broker is much better than having a fixed cluster wide bandwidth per client because that would require a mechanism to share client quota usage among all the brokers. This can be harder to get right than the quota implementation itself!

**Comment by lionelvillard** [comment]
I looked at this but it AFAICT a consumer cannot set quotas so that's a no go. We want to be able to limit the bandwidth from the consumer and per consumer.

**Comment by pierDipi** [comment]
Make sense, thanks for sharing!

**Comment by lionelvillard** [comment]
/remove-lifecycle stale
/reopen

I still think this is a good idea.
