### ISSUE TITLE
Commonly used checkRetry override 

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#398]
**Problem**

The distributed channel has a custom override of the `checkRetry`:
https://github.com/knative-sandbox/eventing-kafka/blob/c41cdae9688ffabf024e575be772096369c3cd3d/pkg/channel/distributed/dispatcher/dispatcher/handler.go#L157-L200

The method is very detailed and covers a lot of cases, than vendored the "default" implementation:

https://github.com/knative-sandbox/eventing-kafka/blob/c41cdae9688ffabf024e575be772096369c3cd3d/vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go#L163

Question: Should we move this up? to the `knative.dev/eventing/pkg/kncloudevents` package? Or also use this on the "consolidated" channel?

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by slinkydeveloper** [comment]
:+1: for me

**Comment by devguyio** [comment]
I think it's useful to use it to eventing and use it in the consolidated channel.

**Comment by matzew** [comment]
> I think it's useful to use it to eventing and use it in the consolidated channel.

the original code is used on the `consolidate` - if we mive thios to eventing, the consolidated gets it.

and than we can get rid of the custom fucntion of the distrubited

**Comment by matzew** [comment]
Added a WIP PR for this, to eventing:

https://github.com/knative/eventing/pull/4890
