### ISSUE TITLE
Kafka Source adapter doesn't get updated when configmaps change

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#399]
**Describe the bug**
Kafka Source adapter doesn't get updated when configmaps change.

Similar to https://github.com/knative-sandbox/eventing-kafka/issues/318 but harder since the Kafka source controller doesn't track the source adapters it creates.

 **Expected behavior**
KafkaSource adapter should get updated when configmaps change.

 **To Reproduce**
- Create a KafkaSource, a source adapter will be created
- Update any of `config-logging`, `config-kafka`, etc. nothing will be reflected on Kafka source adapter since we pass the data of the configmaps as env vars to the adapter deployment with initial creation.

 **Knative release version**
0.20

 **Additional context**
https://github.com/knative-sandbox/eventing-kafka/issues/318

**Comment by aliok** [comment]
@slinkydeveloper @lionelvillard 

This is related to https://github.com/knative-sandbox/eventing-kafka/issues/318.

But this one is harder.
1. We don't mount configmaps as volumes (can't use file watching). --> not possible because adapter lives in user namespace and Kube doesn't allow cross-namespace configmap mount
2. In channel case, we know we have a single dispatcher deployment that we can always find and if we like we can update them. We don't track the adapters we create in the source controller though.
3. Configmap watching is not possible because configmap would live in system namespace and we wouldn't want the adapters living in user namespace to be able to access stuff in system namespace.

So, what I am thinking is:
- Label the source adapter deployments (maybe they're already labeled)
- Fetch them in controller
- Trigger deployment updates on them

What do you think? Any better ideas?

**Comment by slinkydeveloper** [comment]
> Update any of config-logging, config-kafka

We never really cared about that, for a very simple reason: changing these config maps on-fly is **very rare**, these are usually configured once when eventing is setup in the cluster.

> What do you think? Any better ideas?

Sounds good, although as explained above, I'm not sure we should do it.

**Comment by aliok** [comment]
> We never really cared about that, for a very simple reason: changing these config maps on-fly is very rare, these are usually configured once when eventing is setup in the cluster.

Exactly. This is why I wrote an email to the ML if I am trying to solve a problem that's not a big deal.

I will wait a bit more before workingOn/closing this ticket to see what folks think.

**Comment by aliok** [comment]
Closing per https://github.com/knative-sandbox/eventing-kafka/issues/455
