### ISSUE TITLE
[KNEP] Provide various message delivery and ordering guarantees

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#413]
**Description**
Kafka supports multiple message delivery guarantees (no guarantees, at most once, etc...) as well as various ordering guarantees (in consumers). This proposal is to bring these capabilities to Knative Kafka broker, channel and source.

**Comment by yuzisun** [comment]
hi @lionelvillard, what's the plan for this? we are interested in to contribute and discuss the solution.

**Comment by slinkydeveloper** [comment]
TBH @lionelvillard I think this issue requires some more description from you :smile: 

What are we trying to do here? ATM our kafka projects are a bit diverging on the orderding guarantees, kafka broker supports both ordered and unordered delivery, KafkaChannel (I think both impls, but I may be wrong) and Kafka Source supports only ordered delivery. All of them supports partitionKey.

The delivery guarantees (no guarantees, at most once, etc...) are supported by all components (except KafkaSource) through the retries mechanism.

So I wonder, what else you want to address? Is there something specific?
