### ISSUE TITLE
Code convention & linting rules for imports

### ISSUE THREAD

**Issue by devguyio** [knative-sandbox/eventing-kafka#435]
## Description

Would it make sense to agree on a convention for the go imports and maybe set the code style job to verify them? I follow the goimports style and have three blocks each sorted:
1. std
2. 3rd party
3. local package

```go
import (
	"context"
	"fmt"

	"github.com/kelseyhightower/envconfig"
	"go.uber.org/zap"
	"k8s.io/apimachinery/pkg/types"

	"knative.dev/eventing-kafka/pkg/apis/messaging/v1beta1"
	"knative.dev/eventing-kafka/pkg/channel/consolidated/status"
)
```

right now the imports are generally all over the place and varies from one component to another, between PRs, and different committers.

This will make it easier to use some default editor config to do proper imports ordering and formatting, and pay more attention to it in our PRs.

**Comment by matzew** [comment]
sounds good!

**Comment by aliok** [comment]
Sounds good, but is there some tooling for doing this grouping?

**Comment by slinkydeveloper** [comment]
> This will make it easier to use some default editor config to do proper imports ordering and formatting, and pay more attention to it in our PRs.

Which editor? :smile:

**Comment by devguyio** [comment]
> is there some tooling for doing this grouping?
[goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) does the "std lib packages" on top, and custom, empty lines separated groups below. then it automatically imports those groups.

> which editor?
most decent editors have them :smile: [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports)

**Comment by slinkydeveloper** [comment]
goimports is already checked by our linting gh actions script

**Comment by rhuss** [comment]
not sure if there is to be done here specifically (and personally I don't care much as my IDE hides the import from me anyway). I think it's more important to align on conventions about import aliases (if at all). Strangely, the older I get the less I care about code styles or syntactic convention (had too many such battles in my life, won't pick another one if not absolutely needed).

**Comment by n3wscott** [comment]
We already have a standard codestyle github action that runs and will report linting errors. https://github.com/knative-sandbox/.github/blob/main/workflow-templates/knative-style.yaml
