### ISSUE TITLE
[scheduler,mtsource] support for HA 

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#463]
**Problem**
By default, the scheduler tries to allocate vpod replicas onto the same pod. When this pod becomes unavailable, the vpod also become unavailable. Not good.

Tasks:
- [ ] [design - scheduling strategies](https://docs.google.com/document/d/1vR5CVLIVvvVdnlLuS7HtQbE69sYsI9k833pk_aohtmo/edit#heading=h.u20336n3f3mt)
- [ ] implementation

**Comment by matzew** [comment]
Is this for the source? Should it be reflected in the issue name ?

**Comment by lionelvillard** [comment]
yes scheduler = source
