### ISSUE TITLE
`integration-test-mt-source` fails if post-install scripts are executed

### ISSUE THREAD

**Issue by cardil** [knative-sandbox/eventing-kafka#495]
The failing job `integration-test-mt-source` in https://github.com/knative-sandbox/eventing-kafka/pull/467 is apparently my fault. I've added post-install scripts to all installs. But, on mt-source there nothing to migrate, so the job fails with:

```
{"severity":"INFO","timestamp":"2021-04-01T11:13:34.664796968Z","logger":"storage-migrator","caller":"migrate/main.go:53","message":"Migrating group resource kafkachannels.messaging.knative.dev"}
{"severity":"EMERGENCY","timestamp":"2021-04-01T11:13:34.678400082Z","logger":"storage-migrator","caller":"migrate/main.go:55","message":"Failed to migrate: unable to fetch crd kafkachannels.messaging.knative.dev - customresourcedefinitions.apiextensions.k8s.io \"kafkachannels.messaging.knative.dev\" not found","stacktrace":"main.main\n\tknative.dev/eventing-kafka/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go:55\nruntime.main\n\truntime/proc.go:204"} 
```

I'm not sure that post-install scripts should fail if they have nothing to migrate.

Ref.: [integration-test-mt-source build-log.txt L946](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_eventing-kafka/467/pull-knative-sandbox-eventing-kafka-integration-test-mt-source/1377574510290538496#1:build-log.txt%3A946)

_Originally posted by @cardil in https://github.com/knative-sandbox/eventing-kafka/issues/467#issuecomment-811904557_

**Comment by lionelvillard** [comment]
it seems that just installing the KafkaChannel CRD should fix this, right?

**Comment by cardil** [comment]
> it seems that just installing the KafkaChannel CRD should fix this, right?

Right. That's what this issue is about. I think post-install scripts should be safe to apply, even if you didn't deploy the KafkaChannel CRD.
