### ISSUE TITLE
Please create releases for community testing

### ISSUE THREAD

**Issue by AceHack** [knative-sandbox/eventing-kafka#50]
I would like to test this without having to build from source

**Comment by travis-minke-sap** [comment]
Yeah - this is on our radar - we're still ramping up this implementation to be more official.  stay tuned - hopefully soon (we want/need the same thing for our own internal usage as well) - thanks for your patience!

**Comment by travis-minke-sap** [comment]
We're targeting v0.19.0 as the first official release of the `distributed` KafkaChannel implementation.  This will also be the first release of the original `eventing-contrib/kafka` implementations (channel/source/etc) from the eventing-kafka repository.

Until that time we now have nightly builds in place if anyone needs a jumpstart.
https://console.cloud.google.com/storage/browser/knative-nightly/eventing-kafka/latest?authuser=0&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Documentation is admittedly a little rough so don't hesitate to ask any questions in Slack!

**Comment by travis-minke-sap** [comment]
Closing issue as v0.19.0 has been released...

https://github.com/knative-sandbox/eventing-kafka/releases

channel-distributed.yaml

/close
