### ISSUE TITLE
Distributed channel dispatcher/receiver deployments not updated after upgrade

### ISSUE THREAD

**Issue by eric-sap** [knative-sandbox/eventing-kafka#502]
**Describe the bug**
The distributed channel controller has no mechanism to identify and update dispatcher or receiver image changes during reconciliation.  This leaves pods with their original image until the deployments are manually deleted or modified (via "rollout restart" or similar)

 **Expected behavior**
When a KafkaChannel is reconciled, any dispatcher deployments that don't specify the current image should be updated (allowing Kubernetes to do a restart of any affected pods).  Secrets reconciliation and receiver deployments should behave similarly.

 **To Reproduce**
Install an old version of eventing-kafka and upgrade to a newer version.  Notice that when a KafkaChannel is reconciled, the associated dispatcher pod remains running with the old image.

 **Knative release version**
0.21.3

 **Additional context**
Restarting the deployments when the image changes is the bare minimum, but ideally we would like to, during reconciliation, check all of our settings against the existing deployments (not just the image) and reconfigure them as necessary.  In addition, the services would be good to verify/update during this process.

**Comment by aliok** [comment]
We talked about this during #537 but I haven't implemented it myself.

Some thoughts:

> Restarting the deployments when the image changes is the bare minimum, but ideally we would like to, during reconciliation, check all of our settings against the existing deployments (not just the image)

In consolidated channel, the entire deployment spec was compared until https://github.com/knative/eventing-contrib/pull/929 was merged. I don't know what the root cause was for that change though.

**Comment by eric-sap** [comment]
For this issue I wanted to compare certain parts of the spec and containers while ignoring specific individual fields (as opposed to just comparing "the image"), so I used the go-cmp package instead of DeepEqual().  It may some to light that some of the fields I'm not ignoring are causing spurious differences, but so far I haven't found anything in my smoke testing for PR548.
