### ISSUE TITLE
[Consolidated Channel] events potentially undelivered if kafka-ch-dispatcher restarted before first events sent

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka#549]
**Describe the bug**

In a following scenario:
1. Subscription to a KafkaChannel gets Ready
2. kafka-ch-disptacher is restarted (e.g. pod delete)
3. events are sent just as new kafka-ch-disptacher starts

Some of the first events are not delivered to the subscriber.

It seems that if no events were yet commited, the new kafka-ch-dispatcher starts partition consumers at the "-1" offset, even if the subscription was already Ready before.

```
{"level":"info","ts":"2021-04-18T08:05:05.639Z","logger":"kafkachannel-dispatcher","caller":"consumer/consumer_handler.go:76","msg":"Starting partition consumer, topic: knative-messaging-kafka.foobar.channel-eupfwclx, partition: 0, initialOffset: -1","knative.dev/pod":"kafka-ch-dispatcher-5dbdb9bc75-z9xsx","ConsumeGroup":"kafka.foobar.channel-eupfwclx.6231d7a9-9741-4a5c-9cd6-91b7e2fbe64e"}
```

It should probably start at "0" in that case?

 **Expected behavior**
Events should be delivered even if kafka-ch-dispatcher was restarted just before first events were sent

 **To Reproduce**
Steps to reproduce the behavior.

Reproducer: https://github.com/maschmid/kafkachannel-subscription-ready-before-partition-consumers-started ( specifically TestDispatcherRestartBeforeCommitedEvents )

```
make apply
go test -v -run TestDispatcherRestartBeforeCommitedEvents
```

 **Knative release version**
0.20

 **Additional context**
Reproduced on OCP 4.7.6, knative installed with Serverless Operator, with Kafka installed on the OCP cluster with Strimzi.

**Comment by slinkydeveloper** [comment]
I think this one is duplicated of https://github.com/knative-sandbox/eventing-kafka/issues/420

**Comment by aliok** [comment]
For reference, this is the same issue with https://github.com/knative-sandbox/eventing-kafka/issues/411 but in channel.
