### ISSUE TITLE
Allow for passing client cert and key for mTLS when proper CA is used

### ISSUE THREAD

**Issue by mgencur** [knative-sandbox/eventing-kafka#556]
**Describe the bug**
As discussed in https://github.com/knative-sandbox/eventing-kafka/pull/359/files#r616492924 , it would be great to allow for passing the client certificate and key when we use proper CA - to allow for client authentication via certificates. Currently, the key and cert are not read when CA is not explicitly specified. 

 **Expected behavior**
The client key and cert are passed to Eventig Kafka when CA is not specified (when proper CA is inherited from the system).

 **Knative release version**
v0.22.1

**Comment by matzew** [comment]
We still (for only TLS), can use something like [this])https://github.com/knative-sandbox/eventing-kafka/blob/main/test/e2e-common.sh#L467-L470):

```
kubectl create secret --namespace "${SYSTEM_NAMESPACE}" generic strimzi-tls-secret \
    --from-literal=ca.crt="$STRIMZI_CRT" \
    --from-literal=user.crt="$TLSUSER_CRT" \
    --from-literal=user.key="$TLSUSER_KEY"
```

which gives you options for `CA`, `key` _and_ `cert`
