### ISSUE TITLE
Duplicate messages when adapter/dispatcher failed to drain messages "on time"

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka#629]
**Describe the bug**
When a Kafka source spans over one pod, we receive duplicate messages 

 **Expected behavior**
When a Kafka source spans over one pod, we should not receive dups. 

 **To Reproduce**
Create a Kafka source that spans over multiple adapter pod, you should see duplicate messages in the sink. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by lionelvillard** [comment]
`Consumer.Group.Session.Timeout` doc:

```
// The maximum allowed time for each worker to join the group once a rebalance has begun.
// This is basically a limit on the amount of time needed for all tasks to flush any pending
// data and commit offsets. If the timeout is exceeded, then the worker will be removed from
// the group, which will cause offset commit failures (default 60s).
Timeout time.Duration
```

Since it is removed from the group, another member can join the consumer group and process the messages coming from the same partitions as the not-yet-terminated member, causing duplicates.

ConsumerClaim should exit as soon as the session is closed, due to rebalancing or termination (scaling down). We should also put a timeout on requests to avoid long rebalancing delay.

**Comment by steven0711dong** [comment]
@lionelvillard Are we talking about `Rebalance.Timeout` or `Session.Timeout`? The comment was from `Rebalance.Timeout` though.

**Comment by lionelvillard** [comment]
Rebalance.Timeout.

**Comment by steven0711dong** [comment]
Tests from May 28th reveals the dups issue still exists. So I reopened this.

**Comment by lionelvillard** [comment]
Can you describe the steps to reproduce? Do you see errors in the log?

**Comment by steven0711dong** [comment]
For the past several tests I've run, things seem to be working well. We cannot completely avoid duplicate messages simply because of rebalance timeout. Users need to have some kind of limit on their sink delay, otherwise dups will happen.
