### ISSUE TITLE
[source] KafkaSource should by default retry sending events 

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#639]
**Problem**
KafkaSource does not retry sending events when a failure occurs. This is causing events to be lost during upgrade and transient failures.

The first baby step is to bake retries into KafkaSource. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by slinkydeveloper** [comment]
Maybe should kafka source support delivery spec?

**Comment by steven0711dong** [comment]
@slinkydeveloper Moved the discussion to #664. Closing this one because it's a duplicate.
