### ISSUE TITLE
Ability to provide Topic Retention Period on Kafka Channel Spec

### ISSUE THREAD

**Issue by ssandanshi** [knative-sandbox/eventing-kafka#643]
**Problem**
Currently, kafka Channel spec does not allow passing in Retention period at the CRD level.  

The distributed Channel already has a util function to get Retention Periood and uses the default value to create Topic using  admin client. A code change would be required here - https://github.com/knative-sandbox/eventing-kafka/blob/fbb9090ab2a9407cdcbc562d54429c20518930db/pkg/channel/distributed/controller/util/channel.go#L106

For consolidated channel, we need to pass in the retention period under Config Entries like done here -https://github.com/knative-sandbox/eventing-kafka/blob/fbb9090ab2a9407cdcbc562d54429c20518930db/pkg/channel/distributed/controller/kafkachannel/topic.go#L97 while creating topic here - https://github.com/knative-sandbox/eventing-kafka/blob/4027f852ca6ca0ccdad0a062eec7c531d82a9591/pkg/channel/consolidated/reconciler/controller/kafkachannel.go#L544

Other changes to accept the new spec would also be needed.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
A user using Kafka Channel and configuring Retention Period at topic level

**Exit Criteria**
Kafka Channel retention period is configurable at the CR level.

**Comment by slinkydeveloper** [comment]
Sounds like an interesting feature, would you mind providing a PR for it? I can drive you through :smile:

**Comment by ssandanshi** [comment]
Sure, I can work on that PR. There are a few questions on the defaults. I believe this should be an optional config for the Channel spec.
If not provided, the distributed channel will use the default value. But, what would the consolidated channel do? I believe we should not pass it in during topic creation in that case so that it can take the broker retention time by default.

Also I'm not sure about the edge cases and tests. Need some guidance for those.

**Comment by ssandanshi** [comment]
I think I should wait for https://github.com/knative-sandbox/eventing-kafka/pull/622 to be merged in so that I have a common config map to use. It attempts to fix https://github.com/knative-sandbox/eventing-kafka/issues/405.

**Comment by pierDipi** [comment]
This was done in https://github.com/knative-sandbox/eventing-kafka/pull/828, check the new field `spec.retentionDuration`!

Ref: https://github.com/knative-sandbox/eventing-kafka/blob/be3b7de2242f196f13d6d042bd899e10874b0d5e/pkg/apis/messaging/v1beta1/kafka_channel_types.go#L73-L78
