### ISSUE TITLE
Configurable Kafka Client Version

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka#655]
**Describe the bug**
Currently the Kafka version is defaulted to 1.0.0 

 **Expected behavior**
Kafka version should be configurable. It should be per Kafka source 

 **To Reproduce**
Just create a Kafka source and see from the Kafka client config 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by steven0711dong** [comment]
@lionelvillard Kafka version should be per Kafka source right? Because it is a bring your own Kafka instance sort of thing. If so, users should indicate the Kafka version on their CR.

**Comment by aliok** [comment]
KafkaSource (not sure about MT one) reads the Kafka version from `config-kafka` and uses it as the Kafka version to pass to Sarama.

If it is a common thing to use multiple Kafka clusters for KafkaSources within a Kubernetes namespace, yes, we can have them in the KafkaSource CRD. Can we validate if that's the usecase?

**Comment by steven0711dong** [comment]
@aliok I'm not sure about Single tenant, but is Knative Kafka source designed for using the exact same Kafka cluster? If not, then this should be a property on the CR.

**Comment by lionelvillard** [comment]
I would rather rely on [KIP-35](https://cwiki.apache.org/confluence/display/KAFKA/KIP-35+-+Retrieving+protocol+version) to automatically find the protocol version. The user shouldn't have to do that.
