### ISSUE TITLE
Kafka source occasionally gets stuck 

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka#665]
**Describe the bug**
Occasionally a Kafka source gets stuck in a state that the `vreplicas` do not get scaled down. And the kafka source swings between setting up handler and clean up handler

 **Expected behavior**
Allow kafka source to move on 

 **To Reproduce**
It happens occasionally and randomly 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by steven0711dong** [comment]
This is a serious issue. I still have a Kafka source in stuck state since last night with 150Million messages and it's been 9 hours and only less than 10000 messages were consumed. Kafka source seems to be stuck inside Sarama library.

**Comment by aliok** [comment]
I have done similar tests (not 150 million messages) and haven't seen this problem.
It is either a new one, or it is an edge case. Which version are you using @steven0711dong ? Any other hints to reproduce this?

**Comment by steven0711dong** [comment]
continue to monitor. So far I do not see stuck problem ever since the stuck fix was merged. Keep this issue open for a while until we don't see stuck issue for a while.

**Comment by runzexia** [comment]
hi @steven0711dong we seems encountered a similar problem, can you help support which PR fixed this problem

**Comment by lionelvillard** [comment]
The latest PR related to this issue is this one: https://github.com/knative-sandbox/eventing-kafka/pull/649

@runzexia Let's know if this fixes your stuck issue.
