### ISSUE TITLE
[mtsource, scheduler] autoscaler refresh period is too big

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#667]
**Describe the bug**
it takes up to 2mn to increase the number of pods, that's too much.

 **Expected behavior**

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aavarghese** [comment]
@lionelvillard I had done some experiments with the refreshPeriod for HA scheduler and left it as 100 seconds (previously was 10 seconds). This period should only affect how often the adapters scale down and not how often the scaling up is done for pending vreplicas, right?

I'm not seeing the 2 minutes wait for the pods to increase with MAXFILLUP. Anything else to do to reproduce?

**Comment by lionelvillard** [comment]
that's right. Maybe that was just a fluke in my environment. Closing.
