### ISSUE TITLE
Upgrade tests for KafkaSource

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#67]
We need to implement upgrade tests for KafkaSource and KafkaBinding so that in the future we can change the storage version to v1beta1 from v1alpha1.

Best idea is to keep eventing at latest release and only changing the eventing-kafka version. We can in the future run the tests again with eventing head too.

Part of umbrella issue, #65

**Comment by cardil** [comment]
I think this should be modeled similar to eventing and serving upgrade tests. That means upgrading to the latest version from stable and going back.

If we implement migration of API at any point it should do that in that migration period and tests should survive that.

My approach would be to adopt a new upgrade test framework for compose-ability and write some standard pre- post- assertions and continual tests.

To be able to write continual tests, I'm thinking to extend [Wathola testing utility from eventing](https://github.com/knative/eventing/tree/master/test/upgrade#probe-test), so it will be possible to replace its sender transport from HTTP request to a Kafka client. 

That would enable us to send events directly to Kafka topic, so we can configure KafkaSource or/and KafkaBinding and feed cloud events to broker (in future this broker could be backed by KafkaChannel #72), and then to the receiver for validation.

/assign

**Comment by matzew** [comment]
@cardil I agree that using the schema/model from serving/eventing is right

What do you mean with:
> adopt a new upgrade

Also, extending the utils from eventing to have usage on downstream seems good :+1:

**Comment by cardil** [comment]
I could also skip extending testing tools and use KafkaSink. But, KafkaSink isn't in this repo, right?
