### ISSUE TITLE
KafkaSource Spec

### ISSUE THREAD

**Issue by 2020testuser** [knative-sandbox/eventing-kafka#689]
Hi,
Seems like there is a bug in KafkaSource Spec. generation.
I'm getting the below error.
If I have tls enabled and sasl disabled, I get the below error. The sasl key, value attributes must not be included during spec generation. 

Could anyone shed some light to fix the issue, please? Thanks in advance!!

 
Below is the KafkaSourceSpec.

`{\"kind\":\"KafkaSource\",\"apiVersion\":\"sources.knative.dev/v1beta1\",\"metadata\":{\"name\":\"source-name\",\"namespace\":\"testsrc-ns\",\"creationTimestamp\":null},\"spec\":{\"bootstrapServers\":[\"xxx:443\"],\"net\":{\"sasl\":{\"user\":{},\"password\":{},\"type\":{}},\"tls\":{\"enable\":true,\"cert\":{\"secretKeyRef\":{\"name\":\"tls-secret\",\"key\":\"tls.crt\"}},\"key\":{\"secretKeyRef\":{\"name\":\"tls-secret\",\"key\":\"tls.key\"}},\"caCert\":{\"secretKeyRef\":{\"name\":\"ca-secret\",\"key\":\"ca.crt\"}}}},\"topics\":[\"topic1\"],\"consumerGroup\":\"consumer-grp1\",\"sink\":{\"ref\":{\"kind\":\"service\",\"name\":\"test-srv\",\"apiVersion\":\"serving.knative.dev/v1\"}}},\"status\":{}} false []} \n"}`

=====
`%verror from cluster : ctc, admission webhook \"defaulting.webhook.kafka.sources.knative.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"type\""}`

**Comment by 2020testuser** [comment]
@lionelvillard - Thanks!
I create the KafkaSource programmatically using pkg - knative.dev/eventing-kafka/pkg/apis/sources/v1beta1. I get the below error.
`%verror from cluster : ctc, admission webhook \"defaulting.webhook.kafka.sources.knative.dev\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \"type\""}`


Below is my test yaml (which I created based on the output from the kafkasource generation. Based on my yaml testings, below are my findings. Appreciate if you could let me know whether this is bug or I'm missing something. Thanks in advance!

1. Even if I don't include sasl- enable - false during the kafkasource spec generation (in my code), the below section gets added in the generated spec.
`sasl:
      enable: false
      user: {}
      password: {}
      type: {}`

2.  If I remove 'type' under sasl section in the yaml, kafkasource gets created successfully.
3. If I remove  the entire sasl section in the yaml, kafkasource gets created successfully.
4. In the spec generation code, having just tls enabled and not setting sasl enabled : false, the generated kafkasource spec. contained the below sasl section . Even when sasl enabled: false was set in the code, I had the below section in the generated spec.
`   sasl:
      enable: false
      user: {}
      password: {}
      type: {}`
=======
`  
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ks-source-name
  namespace: my-ns
  creationTimestamp: null
spec:
  bootstrapServers:
  - myhost:443
  net:
    sasl:
      enable: false
      user: {}
      password: {}
      type: {}
    tls:
      enable: true
      cert:
        secretKeyRef:
          name: tls-secret
          key: tls.crt
      key:
        secretKeyRef:
          name: tls-secret
          key: tls.key
      caCert:
        secretKeyRef:
          name: ca-secret
          key: ca.crt
  topics:
  - mytopic
  consumerGroup: test-consumergrp
  sink:
    ref:
      kind: service
      name: test-display
      apiVersion: serving.knative.dev/v1
`

**Comment by lionelvillard** [comment]
What version of KafkaSource are you using?
