### ISSUE TITLE
[scheduler] mtadapters may not scale down 

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka#699]
**Describe the bug**
The scheduler does not reassign vreplicas to "lower" pods  (ie: with a lower ordinal), preventing the autoscaler to scale down the mtadapter. 

 **Expected behavior**
The mtadapter should be able to scale down when there are unused pods.

 **To Reproduce**
Steps to reproduce the behavior.
Create 1 KafkaSource CR and scale it to 150. In knative-eventing, observe 2 adapter replicas. Create a second KafkaSource CR. Scale down the first KafkaSource CR to 1. The total number of vreplicas is now 2, spread across the 2 adapter replicas. In theory only one adapter is needed. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by steven0711dong** [comment]
@lionelvillard I think I fixed this issue by sorting the placements right?

**Comment by lionelvillard** [comment]
This issue is about a different scenario. I updated the description. @steven0711dong PTAL and LMK if it makes sense to you.

**Comment by steven0711dong** [comment]
This is the same issue with [#489](https://github.ibm.com/coligo/eventing/issues/489)
