### ISSUE TITLE
Kafka ch controller should not recreate the dispatcher if it is missing

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#708]
**Describe the bug**
Kafka ch controller recreates the Kafka ch dispatcher when it sees the dispatcher deployment is missing and this causing ownership problems when the Kafka channel components are deployed with an operator.

For example, at OpenShift Serverless we install the Knative Kafka components with our operator. 
This operator simply applies the YAML in the manifest, which includes the Kafka ch dispatcher as well. When the installation CR is deleted, operator deletes everything in the manifest YAML including the Kafka ch dispatcher deployment. 

However, Kafka ch dispatcher deployment is sometimes recreated by the Kafka ch controller, if Kubernetes decides to delete the Kafka ch controller pod after the Kafka ch dispatcher deployment. What I mean is, controller often has time to react and recreate the dispatcher deployment before the pod is stopped by Kubernetes.

Our operator, or, basically any operator that installs Knative Kafka components, need to own the dispatcher deployment otherwise it cannot propagate the readiness and it cannot do proper cleanups.

 **Expected behavior**
The issue here is that we have 2 owners for the Kafka ch dispatcher deployment. What we suggest is that Kafka ch controller should only touch the replica count and nothing else. It should not recreate the dispatcher deployment if it is missing.

 **To Reproduce**

 **Knative release version**
0.21

 **Additional context**

**Comment by devguyio** [comment]
> need to own the dispatcher deployment otherwise it cannot propagate the readiness

Can you elaborate more on that? why can't it propagate the readiness otherwise? 

> Kafka ch controller should only touch the replica count and nothing else

Why would the controller touch the replica count? I thought scaling the dispatcher deployment is a user concern, so either via yaml/kubectl or via the operator that installs the channel.

**Comment by aliok** [comment]
> need to own the dispatcher deployment otherwise it cannot propagate the readiness
> Can you elaborate more on that? why can't it propagate the readiness otherwise?

Sure. If you the dispatcher pod is crashing, operator needs to state this in the installation CR (KnativeKafka in OpenShift Serverless case) status. Before, operator wasn't owning the dispatcher pod and there were some scenarios where the image was wrong for the dispatcher but the operator was saying "all good".

> Why would the controller touch the replica count? I thought scaling the dispatcher deployment is a user concern, so either via yaml/kubectl or via the operator that installs the channel.

The idea is that don't start the dispatcher pod unless there's a Kafka channel created. This is done to save resources. Dispatcher pods are shared among Kafka channels, so the traditional "create the pod when channel is created and delete it when the channel is deleted" approach can't be used. For example, for KafkaSource, we create the adapter per source and delete the adapter when source CR is deleted. This is not the case here.

I guess we can even get rid of this optimization and start running the pod with 1 replica directly.

**Comment by devguyio** [comment]
> If the dispatcher pod is crashing, operator needs to state this in the installation CR (KnativeKafka in OpenShift Serverless case) status. 

I think the operator can watch for the status without owning the deployment right? .

IMHO I think this approach is correct. The controller should only care about "is there a ready dispatcher" for the channel status reasons. The yaml (and subsequently the operator) should create/delete/scale the deployment. And have the replicas in the repo config yaml set to 1.

**Comment by aliok** [comment]
> I think the operator can watch for the status without owning the deployment right? .

Yeah, but then we need to do additional checks like **manually** querying the API server for dispatcher deployment existence and checking the status. We don't do that currently.

**Comment by matzew** [comment]
> I guess we can even get rid of this optimization and start running the pod with 1 replica directly.

Even if we set it here to just `1` replica, the deployment it still touched. 

/cc @lionelvillard
