### ISSUE TITLE
[KafkaSource] E2e tests should retry producing events in the kafkacat producer-container 

### ISSUE THREAD

**Issue by devguyio** [knative-sandbox/eventing-kafka#789]
**Problem**
Currently in KafkaSource e2e tests, it creates a `producer-container` Pod that uses kafkacat to produce events. 
https://github.com/knative-sandbox/eventing-kafka/blob/main/test/e2e/helpers/kafka_helper.go#L98

If for whatever recoverable error kafkacat fails to produce the events, it'll fail without retrying. This makes the test sensitive to delays in Kafka replicas sync etc.

**Exit Criteria**
`KafkaSource` e2e tests would retry producing events in case of failures.

**Comment by lionelvillard** [comment]
I wonder if we should deprecate these tests in favor of the rekt tests. Almost everything has been ported to rekt, except the update tests. @devguyio WDYT?
