### ISSUE TITLE
Switch to confluent kafka API instead of sarama

### ISSUE THREAD

**Issue by yuzisun** [knative-sandbox/eventing-kafka#826]
**Describe the bug**
We have been running eventing kafka on production but we run into a few mysterious issues when sarama kafka consumer gets stalled and not able to poll messages from kafka topic despite the fact that the session is still live. Sometimes it never recover and we have to bounce the kafka event source pod to rebalance the partitions in the consumer group, while sometimes it recovers itself in about 15mins, this has happened 3 times in a year time framework.

Sarama is pretty difficult to debug and we could not pinpoint what the issue is, wondering if there is any interest to switch to use the confluent kafka API instead.

 **Expected behavior**
kafka consumer should not be stalled.

 **To Reproduce**
This is pretty hard to reproduce...

 **Knative release version**
0.20.0

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by lionelvillard** [comment]
there is a lot of interests! We've also experienced stalled Kafka consumers and so far we blamed it on slow networking, but couldn't really "prove" it.

Note the eventing-kafka-broker is already based on the confluent Kafka API and I've been told it should be easy to expose the KafkaSource API. Interested?

**Comment by travis-minke-sap** [comment]
We just noticed that we are experiencing "missing" ConsumerGroups with the Distributed KafkaChannel.  Meaning the dispatcher has created the ConsumerGroup (and it existed in Kafka) but somehow the ConsumerGroup disappears in Kafka.  Bouncing the Dispatcher pod will re-create the ConsumerGroup but this is obviously not good ; )

I was wondering if you could clarify what you meant by "stalled" ConsumerGroups - and/or whether anyone has seen what I'm describing above?

**Comment by travis-minke-sap** [comment]
> We just noticed that we are experiencing "missing" ConsumerGroups with the Distributed KafkaChannel. Meaning the dispatcher has created the ConsumerGroup (and it existed in Kafka) but somehow the ConsumerGroup disappears in Kafka. Bouncing the Dispatcher pod will re-create the ConsumerGroup but this is obviously not good ; )

For posterity... I believe the issue I was referring to here is #1043 which has been resolved.
