### ISSUE TITLE
support updates to the kafka secret

### ISSUE THREAD

**Issue by duglin** [knative-sandbox/eventing-kafka#880]
When the secret used by the Kafka source is updated (e.g. the password changes), I believe that we won't pick up the new value until something happens in the system (like a pod in the kafa infra changes) or some other reason causes the Kafka CR to be reconciled. It would be nice if it was a bit more deterministic and the new secret values were picked up immediately.

/cc @lionelvillard

**Comment by aliok** [comment]
I worked on the KafkaChannel on similar thing, but not on KafkaSource. I won't have time to work on this issue but I would be happy to assist the person doing the coding.
