### ISSUE TITLE
Add info about Kafka partitions to Kafka Source for tracing purposes

### ISSUE THREAD

**Issue by aavarghese** [knative-sandbox/eventing-kafka#951]
**Problem**
A short explanation of the problem, including relevant restrictions.

For users of Kafka eventing source who want to understand the performance of their system running eventing with Apache Kafka in various cluster setups like single/multi tenant, single/multi regions etc or for troubleshooting reasons, it will be helpful to provide some partition information (below) to kafka source since only kafka consumer knows form which partition it is reading from. Will be useful to also understand the impact of broker rebalancing from Kafka on eventing. Some useful info are:

1. How the x events being consumed by a Kafka source/consumers were spread across the y partitions in that topic?
2. Partition number that an event was consumed from by a consumer (vreplica) and any other metadata could be added?
3. Other Kafka broker details?

This can be optional information added (users can turn on/off this detail)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

Partition info for each event or group of events is visible in the source, and can be consumed by tools like [KPerf](https://github.com/knative-sandbox/kperf) to measure performance.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve? Unknown

**Additional context (optional)**
Add any other context about the feature request here.

Partition-id could be added as key-value pair to tracestate in https://github.com/cloudevents/spec/blob/v1.0.1/extensions/distributed-tracing.md#tracestate (info from @aslom )

**Comment by aavarghese** [comment]
Setup tracing config with zipkin backend for Kafka source and this is all the info (key/value pairs) being forwarded under `Tags`.

![image](https://user-images.githubusercontent.com/716847/139955913-56ea087f-f108-4627-898d-adf888cb281a.png)

There is no info about the Kafka producer + partitions...

**Comment by lionelvillard** [comment]
this is relevant: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#apache-kafka

In particular `messaging.kafka.partition`
